version: '3'

services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=200' -c shared_buffers=128MB
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5433:5432